language: android
sudo: false
android:
  components:
  - build-tools-25.0.2
  - android-25
  - extra-android-support
  - extra-android-m2repository
before_install:
  - chmod +x gradlew
script:
  - "./gradlew assembleRelease"